Initial defaults chart version tied to controller appVersion
rancher/kubewarden-ui pull request #724
Opened 2024-05-17 16:40 UTC by jordojordo

Fix #721 

The kubewarden-defaults chart install banner was not tied to the installed kubewarden-controller `appVersion`, in order to make this work I restructured the methods used in the Dashboard component into utilities and added a method for finding the compatible defaults chart based on the installed controller's `appVersion`.

https://github.com/rancher/kubewarden-ui/assets/40806497/39ccf533-9927-4966-ae42-3840ca730812

2024-05-20 06:41 UTC, kravciak requested changes
When I refresh page before clicking button I get this result:
[Screencast from 2024-05-20 08-31-23.webm](https://github.com/rancher/kubewarden-ui/assets/538604/79fbd205-197a-4712-a157-3e3ff3916da7)

Also automation produced `[object Object]` (clicking faster):
![Screenshot from 2024-05-20 08-37-08](https://github.com/rancher/kubewarden-ui/assets/538604/40e0649c-be5b-445f-84d5-d07a343b4e49)

2024-05-20 10:54 UTC, aalves08 reviewed
Codewise, lgtm. Let me know once you've addressed @kravciak concern's if you need my approval 🙏

2024-05-20 13:22 UTC, jordojordo commented
I wasn't able to reproduce this, but I added a condition to the banner dependent on the loading state, and to the chart install button to not show unless a compatible chart is found.

2024-05-20 13:49 UTC, kravciak commented
Now I get error in console on refresh (`Install Defaults` button is not visible)

```
fetch.client.js:79 Error in fetch(): TypeError: Cannot read properties of undefined (reading 'cluster/schemaFor')
    at o (kubewardenController.ts:9:14)
    at a.fetch (DefaultsBanner.vue:38:1)
    at a.<anonymous> (fetch.client.js:76:31)
    at p (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.next (regeneratorRuntime.js:69:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:22:9)
    at asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
```

2024-05-21 08:13 UTC, kravciak approved these changes
Works fine now - just one minor issue:
- I install controller 2.0.10 (app v1.11.0) > defaults offered in v1.9.4
- I upgrade controller to 2.0.11 (app v1.12.0) > defaults offered still in 1.9.4

When I refresh page defaults are offered in v2.0.0 which fixes the issue.
This is quite a corner case, I am fine merging like it is if it's not an easy fix.

2024-05-21 12:40 UTC, jordojordo commented
This might be a timing issue. I can revisit this in a later issue.

2024-05-21 12:40 UTC, merged